server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/orders/**
        - id: order-service-cart
          uri: http://order-service:8080
          predicates:
            - Path=/api/cart/**

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

auth-service:
  url: http://auth-service:8080
  blacklist-check-path: /api/auth/blacklist/check

logging:
  level:
    org.springframework.security: DEBUG
