services:
  order-db:
    image: postgres:15
    container_name: order-db
    restart: always
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
    ports:
      - "${ORDER_DB_PORT_ON_HOST}:5432"
    networks:
      - backend
    volumes:
      - order_pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-order-service
    restart: always
    ports:
      - "${ORDER_REDIS_PORT}:6379"
    command: [ "redis-server", "--requirepass", "${ORDER_REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data
    networks:
      - backend

  order-service:
    build: .
    container_name: order-service
    depends_on:
      - order-db
      - redis
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${ORDER_DB_HOST}:${ORDER_DB_PORT}/${ORDER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${ORDER_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_DB_PASSWORD}
    ports:
      - "${ORDER_PORT}:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  redis_data:
  order_pgdata: